[project]
name = "mishkal-ivrit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "thewh1teagle", email = "61390950+thewh1teagle@users.noreply.github.com" }
]
requires-python = ">=3.11"
dependencies = [
    "espeakng-loader>=0.2.4",
    "num2words>=0.5.14",
    "phonemizer-fork>=3.3.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "gradio>=5.15.0",
]

[tool.hatch.build.targets.wheel]
packages = ["mishkal"]