# https://en.wikipedia.org/wiki/Unicode_and_HTML_for_the_Hebrew_alphabet#Compact_table
# https://shapecatcher.com/unicode/block/Alphabetic_Presentation_Forms.html
# https://nakdanpro.dicta.org.il/
# https://regex101.com/
# beged kefet with dagesh (בגד-קפת)

############## VAV #############
[[regex]]
reason = "non pointed letter followed by Vav with Holam"
src = "([ב-ת])וֹ"
dst = "$1o"

[[regex]]
reason = "non pointed letter followed by Vav with Dagesh"
src = "([ב-ת])וּ"
dst = "$1u"

[[regex]]
reason = "word start with Vav and Dagesh"
src = "^(וּ)"
dst = "u"

[[regex]]
reason = "word start with Vav and Holam"
src = "^(וְ)"
dst = "ve"

[[regex]]
reason = "two Vav"
src = "ו[\u0591-\u05BD\u05BF-\u05C2\u05C4-\u05C7]ו"
dst = "vu"

############## YUD #############

[[regex]]
reason = "letter with Hirik followed by Yud. Omit the Yud"
src = "([א-ת]\u05B4)י"
dst = "$1"


# ########## General ##########

[[regex]]
reason = "word start with single Shva"
src = "^([א-ת])\u05B0"
dst = "$1?"

# [[regex]]
# reason = "remove Dagesh from Shin"
# src = "([ש])*\u05BC"
# dst = "$1"