name: check
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Check
        run: |
          uv --help
          # uv sync
          # uv run ruff format --diff
          # uv run ruff check
          # uv run pytest
