name: Push to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Prepare and push to HF
        run: |
            # Prepare space
            mkdir phonemize-in-hebrew
            cd phonemize-in-hebrew
            cp ../examples/editor.py app.py
            echo -e "gradio>=5.15.0\nmishkal-hebrew" >> requirements.txt            
            echo -e "title: Phonemize in Hebrew\n\nemoji: 🐢\n\ncolorFrom: red\n\ncolorTo: green\n\nsdk: gradio\n\nsdk_version: 4.44.0\n\napp_file: app.py\n\npinned: false\n\nlicense: mit" >> README.md

            

            # Initialize git and force push
            git config --global user.email "thewh1teagle"
            git config --global user.name "thewh1teagle"
            git init
            git branch -m master main
            git add .
            git commit -m "latest"
            git remote add space https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME
            git push --force space main
            
        env:
            HF_TOKEN: ${{ secrets.HF_TOKEN }}
            HF_USERNAME: "thewh1teagle"
            SPACE_NAME: "phonemize-in-hebrew"